[package]
name = "moenarchbook-wordcount"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]

[dependencies]
moenarchbook = { path = "../../../..", version = "*" }
serde = "1.0"
serde_derive = "1.0"
